name: BIO392_STRs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - gangstr
  - bowtie2
  - samtools
  - numpy
  - pandas
  - seaborn
  - jupyter
  - pip
  - pip:
    - tral
